name: Call Webhook on Commit

on:
  push:
    branches:
      - '**'  # Trigger on all branches

jobs:
  call-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Call Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"text": "New commit pushed to the repository."}' https://zt89nxrf4qez00ejb4ckhitsk66t5nmg.ui.nabu.casa/api/webhook/pull-down-new-goal-tracker-repo-UomEW2ZQkJ65yNJzao6VCF99